name: Node CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: gengjiawen/gitbook
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: build books
        env:
          QTWEBENGINE_DISABLE_SANDBOX: 1
        run: |
          mkdir dist
          gitbook epub ./ dist/heap-exploitation.epub
          gitbook pdf ./ dist/heap-exploitation.pdf
          gitbook mobi ./ dist/heap-exploitation.mobi
          ls -lh -R dist
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md
